import unittest

from parameterized import parameterized

from MotivePosition import MotivePosition
from Origin import Origin
from PositionInWork import PositionInWork


class MotivePositionTest(unittest.TestCase):
    @parameterized.expand(
        [
            [
                "exactly the same MotivePosition",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "different position",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=123,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "different position in work",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.INVERTED,
                ),
            ],
            [
                "different measure_number but same note number",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=123,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "only different position in work: original and inverted",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.INVERTED,
                ),
            ],
            [
                "self is original other is mirrored and only apart by length",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=123,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=2,
                    ),
                    position_in_work=PositionInWork.MIRRORED,
                ),
            ],
            [
                "self is inverted other is mirrored and only apart by length",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.INVERTED,
                ),
                MotivePosition(
                    position=123,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=2,
                    ),
                    position_in_work=PositionInWork.MIRRORED,
                ),
            ],
        ]
    )
    def test_is_same_position(
        self, name, position: MotivePosition, other: MotivePosition
    ):
        self.assertTrue(position.is_same_position(other))
        self.assertTrue(other.is_same_position(position))

        self.assertTrue(position == other)
        self.assertTrue(other == position)

    @parameterized.expand(
        [
            [
                "different length",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=123,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "different piece title",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="otherPiece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "different part id",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="otherPartId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "different part id",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="other",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "only different note number",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=123,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
            ],
            [
                "other is mirrored and more apart than length",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=123,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=3,
                    ),
                    position_in_work=PositionInWork.MIRRORED,
                ),
            ],
            [
                "other is mirrored and less apart than length",
                MotivePosition(
                    position=0,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=0,
                    ),
                    position_in_work=PositionInWork.ORIGINAL,
                ),
                MotivePosition(
                    position=123,
                    length=3,
                    origin=Origin(
                        piece_title="piece",
                        part_id="partId",
                        voice_id="0",
                        measure_number=0,
                        note_number=1,
                    ),
                    position_in_work=PositionInWork.MIRRORED,
                ),
            ],
        ]
    )
    def test_is_not_same_position(
        self, name, position: MotivePosition, other: MotivePosition
    ):
        self.assertFalse(position.is_same_position(other))
        self.assertFalse(other.is_same_position(position))

        self.assertFalse(position == other)
        self.assertFalse(other == position)


if __name__ == "__main__":
    unittest.main()
